name: Heather Brown•Yoga
favicon: null
layout_spectrum: 0.6448743164073676
typography_spectrum: 0.006191470194607973
title: Heather Brown•Yoga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0abbb5'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6875040454324335
purpose: []
